### PR TITLE
Upgrade to highlight 9.15.10

### PR DESCRIPTION
**Pull request by damageboy**
Update to highlight 9.15.10.

This branch is directly mergeable on top of the current 4.0.3...

### CODE REVIEW

**Comment by damageboy** [comment]
Updated my commit to reflect privacy settings and delete a few additional comments from the 3.x days regarding hljs classes...

**Comment by damageboy** [comment]
Ping?

**Comment by damageboy** [comment]
@evilz Are you around?

**Comment by evilz** [comment]
LGTM

**Pull request merged**
