### PR TITLE
Move to revealjs 3.8.0, bump to 3.5.0

### LINKED ISSUE #248: Upgrade to revealjs 3.8.0 and various package updates
Hi @evilz,

I'm not sure if you are still developing this extension or can devote time to it.

I've made a fork / branch where I've upgraded various dependencies and mostly moved over to revealjs 3.8.0 as part of trying to "get into" this extension and maybe fixing some of the export bugs that people are encoutering (including myself).

Would it be OK for me to submit a PR and for you to review it?

Would you be interested?

### PR DESCRIPTION
**Pull request by damageboy**
closes #248

### CODE REVIEW

**Comment by evilz** [comment]
can you tell me more about what you did, cause there are too many changes ....
does webpack working ?

**Comment by damageboy** [comment]
Webpack is definitely failing right now.

I did include the webpack.config.json but for now I can't figure out why it' insisting on complaining about modules such as vscode that are clearly marked as external.

As for the rest of the changes:

1. Copied reveal.js 3.8.0 in the `lib/reveal.js/3.8.0` folder.
2. Notces you were load the `reveal.orig.js` file from 3.7.0 anyway (although you did have a patched version, which was NOT being used), so I replaced the template file to load the original file from 3.8.0
3. For every plugin that was INSIDE 3.7.0 that was not a built-in part of 3.8.0, I copied it over to 3.8.0
4. Copied the head.min.js that you are using from 3.7.0 to 3.8.0

Everything seems to work locally for me after I `vsce package` and install locally.

As I've said I want to stick my hands into something and see if the whole things survived meeting me.

I intend to work on the export functionality, and perhaps a few more things, but I'll be sure to work through GH issues for the rest of the stuff...

**Comment by damageboy** [comment]
I've managed to get webpack working (finally) but I cant see that it's making a huge difference.
I guess that the number of external files is still rather large although the code is packed.

I'll update the pull request,
Please do some more testing on the new vsix.

I'm testing it with a couple of decks to find any quirks!

**Comment by damageboy** [comment]
I've additionally added initial support for serving precompressed file using express with this module:
https://www.npmjs.com/package/express-static-gzip

**Comment by damageboy** [comment]
Hey @evilz,
I've been using the "3.5.0" version locally and so far everything seems to be OK, definitely not feeling any regressions.

I want to start working on the export, as I feel slightly more confident moving around in vscode extensions and debugging them.

It will be great if we could work together on getting this into the master branch so I can continue with other stuff...

Let me know if I can do anything else to get this reviewed!

**Comment by evilz** [comment]
I try to build the PR on my laptop and it's not working :(
I will take a better look today

**Comment by damageboy** [comment]
From what I remember you have to install webpack globally, as in:
```
npm install -g webpack webpack-cli
```

This is unfortunate, but I don't think I can do anything about it...

**Comment by evilz** [comment]
By the way, I think I m going to replace express with koa, Maybe it will fix some issue of the export

**Comment by damageboy** [comment]
Were you able to build with `vsve package` after installing the webpack global tools?

**Comment by damageboy** [comment]
@evilz Can I somehow help in progressing this thing forward?

**Comment by evilz** [comment]
Do you think you can recreate your PR in more tiny ones ?

- only revealjs
- then webpack
- other ...

**Comment by damageboy** [comment]
Yes.
There wasn't too much in the "other" category.

I will close this PR and submit 2 instead.

What order would you rather start with?

WebPack -> RevealJS
Or in reverse?

**Comment by evilz** [comment]
RevealJS THEN WebPack

**Comment by damageboy** [comment]
Sure thing, will do it later tonight!

**Pull request closed without merging**
