### PR TITLE
Improve html export

### PR DESCRIPTION
**Pull request by tfenster**
I want to have the html export in a different subfolder than the default and I don't want the file explorer to always open on export. Therefore I have added two new settings to enable that behavior but if those settings are unchanged, the extension works as before.

I don't know why GitHub shows the .ts files as completely changed, I only implemented the following changes:

src/Models.ts:
```
<<<
export interface IExtensionOptions {
  slideExplorerEnabled: boolean
  browserPath: string
}
---
export interface IExtensionOptions {
  slideExplorerEnabled: boolean
  browserPath: string
  exportHTMLPath: string
  openFilemanagerAfterHTMLExport: boolean
}
>>>
```

src/ExportHTML.ts;
```
<<<
export const getExportFolderPath = (context: VSCodeRevealContext) => {
  const rootDir = path.dirname(context.editor.document.fileName)
  const exportFolderName = path.basename(context.editor.document.fileName, '.md') + "-export"
  return path.join(rootDir, exportFolderName)
}
---
export const getExportFolderPath = (context: VSCodeRevealContext) => {
  const rootDir = path.dirname(context.editor.document.fileName)
  let exportFolderName = path.basename(context.editor.document.fileName, '.md') + '-export'
  if (context.extensionOptions.exportHTMLPath !== null && context.extensionOptions.exportHTMLPath !== '') {
    exportFolderName = context.extensionOptions.exportHTMLPath
  }
  return path.join(rootDir, exportFolderName)
}
>>>
```

src/commands/exportHTML.ts:
```
<<<
  currentContext.SetInExportMode(() => {
    opn(getExportFolderPath(currentContext))
  })
---
  currentContext.SetInExportMode(() => {
    const path = getExportFolderPath(currentContext)
    if (getExtensionOptions().openFilemanagerAfterHTMLExport) {
      opn(path)
    }
  })
>>>
```

### CODE REVIEW

**Comment by tfenster** [comment]
@evilz Not sure why that build fails or if I can do anything about it? Could you point me into the direction where I need to start looking if the problem is caused by my PR?

**Comment by rdbartram** [comment]
@tfenster I resolved the issue with the Azure build, just need @evilz to decide whether its ok or not. It hadn't worked in master....so wasn't your fault ;)

**Comment by tfenster** [comment]
@rdbartram Still fails for me?

**Comment by tfenster** [comment]
Ah, got it, I thought you were talking about my PR. Thanks

**Comment by evilz** [comment]
Thanks guys ! Let me some time tout check this :+1:

**Comment by evilz** [comment]
Thank :+1:

**Comment by tfenster** [comment]
@evilz Do you have a plan when a new release of the extension will be published?

**Comment by evilz** [comment]
soon ....

**Comment by mponton** [comment]
@evilz I see you are actively working on v3. Will there be a new v2 release including this change published or is the next release v3? Asking for a friend 😄 .

I love the extension but the way, thanks for the great work!

**Comment by vbshift** [comment]
no sorry only V3. 
Actually working on export ....

**Pull request merged**
